name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 21
      uses: actions/setup-node@v2
      with:
        node-version: 21
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build

  run-script:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 21
      uses: actions/setup-node@v2
      with:
        node-version: 21
    - name: Install dependencies
      run: npm ci
    - name: Compile js  
      run: npm run build
